Import 3.8-2.4 release

diff --git a/uclinux-rootfs/skel/bin/pml b/uclinux-rootfs/skel/bin/pml
--- a/uclinux-rootfs/skel/bin/pml
+++ b/uclinux-rootfs/skel/bin/pml
@@ -1,29 +1,33 @@
 #!/bin/bash
 
+set -e
+
+waketimer=/sys/devices/*.waketimer
+power_sysfs=/sys/power/state
+cpu_sysfs=/sys/devices/system/cpu
+
 # set defaults
 loops=1
 mode=none
-tp1=1
-flags=5
+tp_all=1
 cycle_tp=
-sleep_sec=
+delay_sec=
 command=
 pm_mode=standby
-cpu_rate=1
+wakeup_time=1
 
 function usage
 {
 	echo "pml: power management script version 1.0"
-	echo "Usage: pml [-lN] [-mMODE] [-tchd] [-fX] [-sN] [-rN]"
+	echo "Usage: pml [-lN] [-mMODE] [-tchd] [-sN] [-wN]"
 	echo "where:"
 	echo "    -lN    - number of loops (decimal:1); negative value - infinite loop"
 	echo "    -mMODE - system suspend debug mode (none, core, platform, devices, freezer:none)"
 	echo "    -d     - deep standby (s3)"
-	echo "    -rN    - change cpu clock divider while executing suspend (1,2,4,8,16 default:1)"
-	echo "    -t     - turn TP1 off before test (no)"
-	echo "    -c     - hotplug-cycle TP1 after each iteration (no)"
-	echo "    -fX    - option flags to pass to system suspend (hex:0)"
+	echo "    -t     - turn secondary CPUs off before test (no)"
+	echo "    -c     - hotplug-cycle secondary CPUs after each iteration (no)"
 	echo "    -sN    - seconds to sleep between iterations (decimal:0)"
+	echo "    -wN    - seconds to wait before waking up (decimal:3)"
 	echo "    -xCMD  - execute command after each iteration"
 	echo "    -XCMD  - execute command after each iteration, quit if the command fails"
 	echo "    -h     - show this message"
@@ -35,12 +39,44 @@ function failure
 	exit
 }
 
+function supported_pmmodes {
+	cat $power_sysfs
+}
+
+function supports_pmmode {
+	state=$1
+	for s in `supported_pmmodes`
+	do
+		[ $s = $state ] && return 0
+	done
+	return 1
+}
+
+function set_sleep_timeout {
+	timeout=$1
+	[ $timeout -lt 0 ] && echo "Invalid timeout: $timeout" && return 1
+	echo enabled > $waketimer/power/wakeup
+	echo $timeout > $waketimer/timeout
+}
+
+function set_cpus_power {
+	online=$1
+	for cpu in $cpu_sysfs/cpu[1-9]*
+	do
+		if [ `cat $cpu/online` -eq $online ]; then continue; fi
+		if [ $online -eq 0 ]; then
+			echo "Power down `basename $cpu`"
+		else
+			echo "Power up `basename $cpu`"
+		fi
+		echo $online > $cpu/online
+	done
+}
+
 quit_on_failure=false
-while getopts "hl:m:tf:cs:x:X:dr:" option
+while getopts "hl:m:tcs:w:x:X:d" option
 do
 	case $option in
-	r)
-		cpu_rate=$OPTARG ;;
 	d)
 		pm_mode=mem ;;
 	x)
@@ -55,46 +91,53 @@ do
 	m)
 		mode=$OPTARG ;;
 	t)
-		tp1=0 ;;
-	f)
-		flags=$OPTARG ;;
+		tp_all=0 ;;
 	c)
 		cycle_tp=1 ;;
 	s)
-	sleep_sec=$OPTARG ;;
+		delay_sec=$OPTARG ;;
+	w)
+		wakeup_time=$OPTARG ;;
 	h|*)
 	usage
 	exit ;;
 	esac
 done
 
+if ! supports_pmmode "$pm_mode"; then
+	echo "Power state \"$pm_mode\" not supported (supported: `supported_pmmodes`)"
+	exit 1
+fi
+
 if [ ! -f /sys/power/pm_test ] ; then
-	echo "Debug PM is not enabled. To enable partial suspend, rebuild kernel with CONFIG_PM_DEBUG"
+	if [ "$mode" != "none" ]; then
+		echo "Debug PM is not enabled. To enable partial suspend, rebuild kernel with CONFIG_PM_DEBUG"
+	fi
 else
 	echo $mode > /sys/power/pm_test
 fi
 
-pmtest tp1 $tp1
+set_cpus_power $tp_all
+
+set_sleep_timeout $wakeup_time
 
 function one_pass
 {
 	passnum=$1
-	totalnum=$2	
-	echo Pass $passnum$totalnum, mode=$mode, tp1=$tp1, flags=$flags, cycle_tp=$cycle_tp, sleep=$sleep_sec
-	echo $cpu_rate > /sys/devices/platform/brcmstb/cpu_div
-	echo $flags > /sys/devices/platform/brcmstb/standby_flags
-	echo $pm_mode > /sys/power/state
-	echo 1 > /sys/devices/platform/brcmstb/cpu_div
+	totalnum=$2
+	echo "Pass $passnum$totalnum, mode=$mode, tp_all=$tp_all, cycle_tp=$cycle_tp, sleep=$delay_sec, wakeup_time=$wakeup_time"
+	echo $pm_mode > $power_sysfs
 	if [ ! -z "$cycle_tp" ] ; then
-		echo "Hotplug-cycling tp1..."
-		pmtest tp1 0; pmtest tp1 1; pmtest tp1 $tp1;
+		set_cpus_power 0
+		set_cpus_power 1
+		set_cpus_power $tp_all
 	fi
 	if [ ! -z "$command" ] ; then
 		eval $command
 		[ $? -ne 0 ] && [ "$quit_on_failure" == "true" ] && failure
 	fi
-	if [ ! -z "$sleep_sec" ] ; then
-		sleep $sleep_sec
+	if [ ! -z "$delay_sec" ] ; then
+		sleep $delay_sec
 	fi
 	echo "------------------------------"
 }
